spring:
  application:
    name: filter-service
  cloud:
    config:
<<<<<<< HEAD
      profile: ${PROFILE}
  config:
    import: configserver:http://localhost:8888,optional:file:.env[.properties]
=======
      profile: dev
  config:
    import: configserver:http://localhost:8888
    
 
>>>>>>> 85ae80248b127cbb1aa9e0a0224b008688395ea4
