server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                default-label: master
                git:
                    uri: https://github.com/ElifNidaKarakas/microservice-config-server
    profiles:
        active: ${PROFILE}